apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/termination-reencrypt
  - ../../components/enable-notifications
  - ../../components/gitops-admins
  - ../../components/health-check-odf
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds

patches:
  - path: openshift-gitops-resources-patch.yaml
  - path: openshift-gitops-rbac-patch.yaml
