apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - gitops-admin-group.yaml


components:
  - ../../components/annotation-resource-tracking
  - ../../components/application-controller-cluster-admin
  - ../../components/enable-notifications
  - ../../components/health-check-odf
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds
  - ../../components/termination-reencrypt

patches:
  - path: openshift-gitops-resources-patch.yaml
  - path: openshift-gitops-rbac-patch.yaml
