apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
spec:
  collection:
    type: fluentd
  logStore:
    elasticsearch:
      resources:
        requests:
          memory: 2Gi
      storage:
        size: 200G
        # storageClassName: replace-me
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
    retentionPolicy:
      application:
        maxAge: 7d
    type: elasticsearch
  visualization:
    kibana:
      replicas: 1
    type: kibana
  managementState: Managed
