apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - aap-admins-group.yaml
  - aap-edit-ns-rolebinding.yaml
  - adhoc-ops-group.yaml
  - lab-cluster-admins-group.yaml
  - lab-cluster-admins-rolebinding.yaml
  - lab-cluster-readers-group.yaml
  - lab-cluster-readers-rolebinding.yaml

patchesJson6902:
  - target:
      group: machineconfiguration.openshift.io
      version: v1
      kind: MachineConfig
      name: 99-master-ssh
    path: patch-ssh.yaml
  - target:
      group: machineconfiguration.openshift.io
      version: v1
      kind: MachineConfig
      name: 99-worker-ssh
    path: patch-ssh.yaml
