apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-adrezni
              namespace: openshift-gitops
              path: tenants/hou-edge/adrezni/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-ai-sensor
              namespace: openshift-gitops
              path: tenants/hou-edge/ai-sensor/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-backstage
              namespace: openshift-gitops
              path: tenants/hou-edge/backstage/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-bkoz
              namespace: openshift-gitops
              path: tenants/hou-edge/bkoz/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-chevron
              namespace: openshift-gitops
              path: tenants/hou-edge/chevron/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-cnorville90
              namespace: openshift-gitops
              path: tenants/hou-edge/cnorville90/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-codekow
              namespace: openshift-gitops
              path: tenants/hou-edge/codekow/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-gsisa
              namespace: openshift-gitops
              path: tenants/hou-edge/gsisa/overlays/default
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-jarcher
              namespace: openshift-gitops
              path: tenants/hou-edge/jarcher/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-osdu
              namespace: openshift-gitops
              path: tenants/hou-edge/osdu/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-smarthub
              namespace: openshift-gitops
              path: tenants/hou-edge/smarthub/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-thomasphall
              namespace: openshift-gitops
              path: tenants/hou-edge/thomasphall/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-troyer
              namespace: openshift-gitops
              path: tenants/hou-edge/troyer/charts/tenant-projects
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 4
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 10m
      source:
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{values.namespace}}'
