---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
  - enable-console-plugin-job.yaml
  - enable-console-plugin-rbac.yaml
  - enable-console-plugin-sa.yaml
  - openshift-logging-namespace.yaml
  - openshift-logging-operatorgroup.yaml
  - openshift-logging-subscription.yaml
