apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-adrezni
              namespace: openshift-gitops
              path: tenants/hou-edge/adrezni/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-archer
              namespace: openshift-gitops
              path: tenants/hou-edge/archer/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-bkoz
              namespace: openshift-gitops
              path: tenants/hou-edge/bkoz/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-chaosmonkey
              namespace: openshift-gitops
              path: tenants/hou-edge/chaosmonkey/charts/tenant-projects
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: tenant-projects-hall
              namespace: openshift-gitops
              path: tenants/hou-edge/hall/charts/tenant-projects
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        # retry:
        #   limit: 2
        #   backoff:
        #     duration: 5s
        #     factor: 2
        #     maxDuration: 10m
      source:
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{values.namespace}}'
