- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-aap-instance
        namespace: openshift-gitops
        # without kustomize: oc apply -f <path>
        # path: components/configs/simple/aap-instance
        # with kustomize: oc apply -k <path>
        path: components/operators/ansible-automation-platform-operator/instance/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-adhoc-admin
        namespace: openshift-gitops
        path: components/configs/adhoc/base
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-console
        namespace: openshift-gitops
        path: components/configs/console/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-certs
        namespace: openshift-gitops
        path: components/configs/cluster-certs/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-namespaces
        namespace: openshift-gitops
        path: components/configs/namespaces/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-oauth
        namespace: openshift-gitops
        path: components/configs/oauth/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-rbac
        namespace: openshift-gitops
        path: components/configs/rbac/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-sandbox-cleanup
        namespace: openshift-gitops
        path: components/configs/simple/sandbox-cleanup
