- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-console
        namespace: openshift-gitops
        path: components/configs/console/base
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-certs
        namespace: openshift-gitops
        path: components/configs/cluster-certs/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-namespaces
        namespace: openshift-gitops
        path: components/configs/namespaces/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-oauth
        namespace: openshift-gitops
        path: components/configs/oauth/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-rbac
        namespace: openshift-gitops
        path: components/configs/rbac/overlays/hou-edge
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-sandbox-cleanup
        namespace: openshift-gitops
        path: components/configs/simple/sandbox-cleanup
