apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

bases:
- ../../base

resources:
- client-sealed-secret.yaml

# Patch cluster specific
patchesJson6902:
  - path: patch-idp.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1